### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by EricRabil** [sauidsd/sua821#9]
pls

**Comment by AppleBetas** [comment]
RTRTRTRTRTRT

**Comment by 1Conan** [comment]
Even though what iCUD did is "bad", this is rude.

**Comment by AppleBetas** [comment]
Does someone profiting off of others' hard work really deserve politeness?

**Comment by 1Conan** [comment]
I meant that this is just over the top. Saying that he should die because of this is just not right.
